debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.connection.host=job-queue
debezium.sink.rabbitmq.connection.port=5672
debezium.sink.rabbitmq.connection.username=${RABBITMQ_DEFAULT_USER}
debezium.sink.rabbitmq.connection.password=${RABBITMQ_DEFAULT_PASS}
debezium.sink.rabbitmq.exchange=eventa.event.jobs
debezium.sink.rabbitmq.routingKey.source=key
debezium.sink.rabbitmq.deliveryMode=2
debezium.sink.rabbitmq.ackTimeout=30000

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=event-database
debezium.source.database.port=5432
debezium.source.database.user=${POSTGRES_USER}
debezium.source.database.password=${POSTGRES_PASSWORD}
debezium.source.database.dbname=${POSTGRES_DB}
debezium.source.topic.prefix=eventa-event-rabbitmq-cdc
debezium.source.plugin.name=pgoutput
debezium.source.slot.name=eventa_event_rabbitmq_cdc
debezium.source.publication.name=eventa_event_rabbitmq_cdc
debezium.source.publication.autocreate.mode=filtered
debezium.source.table.include.list=public.event_job_outbox
debezium.source.tombstones.on.delete=false
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=1000

debezium.format.key=simplestring
debezium.format.value=json
debezium.format.value.schemas.enable=false

debezium.transforms=outbox
debezium.transforms.outbox.type=io.debezium.transforms.outbox.EventRouter
debezium.transforms.outbox.route.by.field=aggregate_type
debezium.transforms.outbox.route.topic.replacement=$${routedByValue}
debezium.transforms.outbox.table.field.event.id=id
debezium.transforms.outbox.table.field.event.key=routing_key
debezium.transforms.outbox.table.field.event.payload=payload
debezium.transforms.outbox.table.field.event.type=event_type
debezium.transforms.outbox.table.expand.json.payload=true
debezium.transforms.outbox.table.op.invalid.behavior=fatal
