export const ADMIN_PASSWORD_RESET_STATE = Symbol('ADMIN_PASSWORD_RESET_STATE');

export const ADMIN_PASSWORD_RESET_CODE_TTL_MS = 15 * 60 * 1_000;
export const ADMIN_PASSWORD_RESET_CODE_MAX_GUESSES = 5;
export const ADMIN_PASSWORD_RESET_REQUEST_COOLDOWN_MS = 60 * 1_000;
