export const ADMIN_ACTIVATION_OTP_STATE = Symbol('ADMIN_ACTIVATION_OTP_STATE');
export const ADMIN_AUTH_JOB_PUBLISHER = Symbol('ADMIN_AUTH_JOB_PUBLISHER');

export const ADMIN_ACTIVATION_OTP_MAX_GUESSES = 5;
export const ADMIN_ACTIVATION_OTP_TTL_MS = 15 * 60 * 1_000;
export const ADMIN_ACTIVATION_REQUEST_COOLDOWN_MS = 60 * 1_000;
export const ADMIN_ACTIVATION_GRANT_TTL_MS = 10 * 60 * 1_000;
