packages:
  - apps/*
  - services/*
  - packages/*

allowBuilds:
  '@bufbuild/buf': true
  '@nestjs/core': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  protobufjs: true

injectWorkspacePackages: true
