export const ADMIN_ACTIVATION_MAX_DELIVERY_ATTEMPTS = 3;
export const ADMIN_ACTIVATION_RETRY_DELAYS_MS = [5_000, 30_000] as const;
export const ADMIN_ACTIVATION_CONSUMER_PREFETCH = 8;
export const ADMIN_ACTIVATION_JOB_MAX_BYTES = 4_096;
