export const AUTH_EMAIL_DELIVERY_REPOSITORY = Symbol(
  'AUTH_EMAIL_DELIVERY_REPOSITORY',
);
export const EMAIL_DELIVERY_PROVIDER = Symbol('EMAIL_DELIVERY_PROVIDER');
export const ATTENDEE_PASSWORD_RESET_CONSUMER = Symbol(
  'ATTENDEE_PASSWORD_RESET_CONSUMER',
);
export const ADMIN_PASSWORD_RESET_CONSUMER = Symbol(
  'ADMIN_PASSWORD_RESET_CONSUMER',
);

export const AUTH_EMAIL_MAX_DELIVERY_ATTEMPTS = 3;
export const AUTH_EMAIL_PROCESSING_LEASE_MS = 30_000;
