export const EVENT_CANCELLATION_EMAIL_OPERATION =
  'notification.event_cancellation_email';
export const EVENT_CANCELLATION_EMAIL_DELIVERY_OPERATION =
  'notification.event_cancellation_email_delivery';
export const EVENT_CANCELLATION_EMAIL_EXCHANGE = 'eventa.notification.jobs';
export const EVENT_CANCELLATION_EMAIL_QUEUE =
  'eventa.notification.event-cancellation-email.v1';
export const EVENT_CANCELLATION_EMAIL_JOB_TYPE =
  'notification.event-cancellation-email.v1';
export const EVENT_CANCELLATION_EMAIL_MAX_DELIVERY_ATTEMPTS = 3;
export const EVENT_CANCELLATION_EMAIL_RETRY_DELAYS_MS = [5_000, 30_000];
export const EVENT_CANCELLATION_EMAIL_PROCESSING_LEASE_MS = 30_000;
export const EVENT_CANCELLATION_EMAIL_CONSUMER_PREFETCH = 8;
export const EVENT_CANCELLATION_EMAIL_JOB_MAX_BYTES = 2_048;
export const CONSUMER_RETRY_MIN_MS = 1_000;
export const CONSUMER_RETRY_MAX_MS = 30_000;
export const SHUTDOWN_WAIT_MS = 5_000;
export const CANCELLATION_EMAIL_DELIVERY_REPOSITORY = Symbol(
  'CANCELLATION_EMAIL_DELIVERY_REPOSITORY',
);
export const ATTENDEE_CONTACT_PROVIDER = Symbol('ATTENDEE_CONTACT_PROVIDER');
export const EVENT_SUMMARY_PROVIDER = Symbol('EVENT_SUMMARY_PROVIDER');
export const EVENT_CANCELLATION_EMAIL_CONSUMER = Symbol(
  'EVENT_CANCELLATION_EMAIL_CONSUMER',
);
export const IDENTITY_GRPC_CLIENT = Symbol('IDENTITY_GRPC_CLIENT');
export const EVENT_GRPC_CLIENT = Symbol('EVENT_GRPC_CLIENT');
