export const EMAIL_VERIFICATION_DELIVERY_REPOSITORY = Symbol(
  'EMAIL_VERIFICATION_DELIVERY_REPOSITORY',
);
export const EMAIL_VERIFICATION_EMAIL_SENDER = Symbol(
  'EMAIL_VERIFICATION_EMAIL_SENDER',
);
export const EMAIL_CLIENT = Symbol('EMAIL_CLIENT');

export const EMAIL_VERIFICATION_MAX_DELIVERY_ATTEMPTS = 3;
export const EMAIL_VERIFICATION_PROCESSING_LEASE_MS = 30_000;
export const EMAIL_VERIFICATION_RETRY_DELAYS_MS = [5_000, 30_000] as const;
export const EMAIL_VERIFICATION_JOB_MAX_BYTES = 2_048;
export const EMAIL_VERIFICATION_CONSUMER_PREFETCH = 8;
