export const EMAIL_VERIFICATION_MAX_DELIVERY_ATTEMPTS = 3;
export const EMAIL_VERIFICATION_RETRY_DELAYS_MS = [5_000, 30_000] as const;
export const EMAIL_VERIFICATION_JOB_MAX_BYTES = 2_048;
export const EMAIL_VERIFICATION_CONSUMER_PREFETCH = 8;
