export const PASSWORD_RESET_DELIVERY_REPOSITORY = Symbol(
  'PASSWORD_RESET_DELIVERY_REPOSITORY',
);
export const PASSWORD_RESET_EMAIL_SENDER = Symbol(
  'PASSWORD_RESET_EMAIL_SENDER',
);

export const PASSWORD_RESET_MAX_DELIVERY_ATTEMPTS = 3;
export const PASSWORD_RESET_PROCESSING_LEASE_MS = 30_000;
export const PASSWORD_RESET_RETRY_DELAYS_MS = [5_000, 30_000] as const;
export const PASSWORD_RESET_CONSUMER_PREFETCH = 8;
export const PASSWORD_RESET_JOB_MAX_BYTES = 4_096;
