// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: issuance.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimCancellationEvent = `-- name: ClaimCancellationEvent :one
INSERT INTO ticket_cancellation_inbox (message_id, event_id, event_type)
VALUES ($1, $2, 'event.cancelled.v1')
ON CONFLICT (message_id) DO NOTHING
RETURNING message_id
`

type ClaimCancellationEventParams struct {
	MessageID pgtype.UUID
	EventID   pgtype.UUID
}

func (q *Queries) ClaimCancellationEvent(ctx context.Context, arg ClaimCancellationEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimCancellationEvent, arg.MessageID, arg.EventID)
	var message_id pgtype.UUID
	err := row.Scan(&message_id)
	return message_id, err
}

const claimIssuanceEvent = `-- name: ClaimIssuanceEvent :one
INSERT INTO ticket_issuance_inbox (event_id, event_type)
VALUES ($1, 'commerce.order-paid.v1')
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id
`

func (q *Queries) ClaimIssuanceEvent(ctx context.Context, eventID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimIssuanceEvent, eventID)
	var event_id pgtype.UUID
	err := row.Scan(&event_id)
	return event_id, err
}

const createCheckInOutbox = `-- name: CreateCheckInOutbox :exec
INSERT INTO ticket_check_in_outbox (event_id, ticket_id, event_type, occurred_at, aggregate_type, aggregate_id, payload)
VALUES ($1::uuid, $2::uuid, 'ticket.checked-in.v1', $3,
    'eventa.ticket.check-in.v1', $2::uuid,
    (SELECT jsonb_build_object('messageId', $1::uuid, 'eventId', event_id,
        'ticketId', id, 'attendeeId', attendee_id, 'checkedInAt', checked_in_at,
        'type', 'ticket.checked-in.v1')
     FROM issued_tickets WHERE id = $2::uuid))
`

type CreateCheckInOutboxParams struct {
	EventID    pgtype.UUID
	TicketID   pgtype.UUID
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) CreateCheckInOutbox(ctx context.Context, arg CreateCheckInOutboxParams) error {
	_, err := q.db.Exec(ctx, createCheckInOutbox, arg.EventID, arg.TicketID, arg.OccurredAt)
	return err
}

const createIssuedTicket = `-- name: CreateIssuedTicket :exec
INSERT INTO issued_tickets (id, order_id, attendee_id, event_id, ticket_type_id, unit_index, qr_token, qr_secret_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateIssuedTicketParams struct {
	ID           pgtype.UUID
	OrderID      pgtype.UUID
	AttendeeID   pgtype.UUID
	EventID      pgtype.UUID
	TicketTypeID pgtype.UUID
	UnitIndex    int32
	QrToken      []byte
	QrSecretHash []byte
}

func (q *Queries) CreateIssuedTicket(ctx context.Context, arg CreateIssuedTicketParams) error {
	_, err := q.db.Exec(ctx, createIssuedTicket,
		arg.ID,
		arg.OrderID,
		arg.AttendeeID,
		arg.EventID,
		arg.TicketTypeID,
		arg.UnitIndex,
		arg.QrToken,
		arg.QrSecretHash,
	)
	return err
}

const createRevocationOutbox = `-- name: CreateRevocationOutbox :exec
INSERT INTO ticket_revocation_outbox (event_id, aggregate_type, aggregate_id, event_type, payload, occurred_at)
SELECT $1::uuid, 'eventa.ticket.revoked.v1', t.id, 'ticket.revoked.v1',
    jsonb_build_object('messageId', $1::uuid, 'eventId', t.event_id,
        'ticketId', t.id, 'attendeeId', t.attendee_id, 'revokedAt', now(),
        'type', 'ticket.revoked.v1'), now()
FROM issued_tickets t WHERE t.id = $2::uuid
`

type CreateRevocationOutboxParams struct {
	MessageID pgtype.UUID
	TicketID  pgtype.UUID
}

func (q *Queries) CreateRevocationOutbox(ctx context.Context, arg CreateRevocationOutboxParams) error {
	_, err := q.db.Exec(ctx, createRevocationOutbox, arg.MessageID, arg.TicketID)
	return err
}

const findTicketForCheckIn = `-- name: FindTicketForCheckIn :one
SELECT id, order_id, attendee_id, event_id, ticket_type_id, unit_index, status,
       issued_at, qr_token, checked_in_at, checked_in_by
FROM issued_tickets
WHERE qr_secret_hash = $1
FOR UPDATE
`

type FindTicketForCheckInRow struct {
	ID           pgtype.UUID
	OrderID      pgtype.UUID
	AttendeeID   pgtype.UUID
	EventID      pgtype.UUID
	TicketTypeID pgtype.UUID
	UnitIndex    int32
	Status       string
	IssuedAt     pgtype.Timestamptz
	QrToken      []byte
	CheckedInAt  pgtype.Timestamptz
	CheckedInBy  pgtype.UUID
}

func (q *Queries) FindTicketForCheckIn(ctx context.Context, qrSecretHash []byte) (FindTicketForCheckInRow, error) {
	row := q.db.QueryRow(ctx, findTicketForCheckIn, qrSecretHash)
	var i FindTicketForCheckInRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AttendeeID,
		&i.EventID,
		&i.TicketTypeID,
		&i.UnitIndex,
		&i.Status,
		&i.IssuedAt,
		&i.QrToken,
		&i.CheckedInAt,
		&i.CheckedInBy,
	)
	return i, err
}

const isEventCancelled = `-- name: IsEventCancelled :one
SELECT EXISTS (SELECT 1 FROM ticket_cancelled_events WHERE event_id = $1) AS cancelled
`

func (q *Queries) IsEventCancelled(ctx context.Context, eventID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isEventCancelled, eventID)
	var cancelled bool
	err := row.Scan(&cancelled)
	return cancelled, err
}

const listIssuedTicketsByAttendee = `-- name: ListIssuedTicketsByAttendee :many
SELECT id, order_id, attendee_id, event_id, ticket_type_id, unit_index, status, issued_at, qr_token
FROM issued_tickets
WHERE attendee_id = $1
  AND ($2::timestamptz IS NULL OR (issued_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY issued_at DESC, id DESC
LIMIT $4
`

type ListIssuedTicketsByAttendeeParams struct {
	AttendeeID pgtype.UUID
	Column2    pgtype.Timestamptz
	Column3    pgtype.UUID
	Limit      int32
}

type ListIssuedTicketsByAttendeeRow struct {
	ID           pgtype.UUID
	OrderID      pgtype.UUID
	AttendeeID   pgtype.UUID
	EventID      pgtype.UUID
	TicketTypeID pgtype.UUID
	UnitIndex    int32
	Status       string
	IssuedAt     pgtype.Timestamptz
	QrToken      []byte
}

func (q *Queries) ListIssuedTicketsByAttendee(ctx context.Context, arg ListIssuedTicketsByAttendeeParams) ([]ListIssuedTicketsByAttendeeRow, error) {
	rows, err := q.db.Query(ctx, listIssuedTicketsByAttendee,
		arg.AttendeeID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuedTicketsByAttendeeRow
	for rows.Next() {
		var i ListIssuedTicketsByAttendeeRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.AttendeeID,
			&i.EventID,
			&i.TicketTypeID,
			&i.UnitIndex,
			&i.Status,
			&i.IssuedAt,
			&i.QrToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsForRevocation = `-- name: ListTicketsForRevocation :many
SELECT id FROM issued_tickets
WHERE event_id = $1 AND status <> 'revoked'
ORDER BY id FOR UPDATE
`

func (q *Queries) ListTicketsForRevocation(ctx context.Context, eventID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listTicketsForRevocation, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEvent = `-- name: LockEvent :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockEvent(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockEvent, dollar_1)
	return err
}

const markCancellationProcessed = `-- name: MarkCancellationProcessed :exec
UPDATE ticket_cancellation_inbox SET status = 'processed', processed_at = now()
WHERE message_id = $1
`

func (q *Queries) MarkCancellationProcessed(ctx context.Context, messageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markCancellationProcessed, messageID)
	return err
}

const markEventCancelled = `-- name: MarkEventCancelled :exec
INSERT INTO ticket_cancelled_events (event_id, cancellation_message_id)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
`

type MarkEventCancelledParams struct {
	EventID               pgtype.UUID
	CancellationMessageID pgtype.UUID
}

func (q *Queries) MarkEventCancelled(ctx context.Context, arg MarkEventCancelledParams) error {
	_, err := q.db.Exec(ctx, markEventCancelled, arg.EventID, arg.CancellationMessageID)
	return err
}

const markIssuanceProcessed = `-- name: MarkIssuanceProcessed :exec
UPDATE ticket_issuance_inbox
SET status = 'processed', processed_at = now()
WHERE event_id = $1
`

func (q *Queries) MarkIssuanceProcessed(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markIssuanceProcessed, eventID)
	return err
}

const markTicketCheckedIn = `-- name: MarkTicketCheckedIn :exec
UPDATE issued_tickets
SET status = 'checked_in', checked_in_at = $2, checked_in_by = $3
WHERE id = $1 AND status = 'issued'
`

type MarkTicketCheckedInParams struct {
	ID          pgtype.UUID
	CheckedInAt pgtype.Timestamptz
	CheckedInBy pgtype.UUID
}

func (q *Queries) MarkTicketCheckedIn(ctx context.Context, arg MarkTicketCheckedInParams) error {
	_, err := q.db.Exec(ctx, markTicketCheckedIn, arg.ID, arg.CheckedInAt, arg.CheckedInBy)
	return err
}

const revokeTicket = `-- name: RevokeTicket :exec
UPDATE issued_tickets SET status = 'revoked'
WHERE id = $1 AND event_id = $2 AND status <> 'revoked'
`

type RevokeTicketParams struct {
	ID      pgtype.UUID
	EventID pgtype.UUID
}

func (q *Queries) RevokeTicket(ctx context.Context, arg RevokeTicketParams) error {
	_, err := q.db.Exec(ctx, revokeTicket, arg.ID, arg.EventID)
	return err
}
