// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: issuance.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIssuanceEvent = `-- name: ClaimIssuanceEvent :one
INSERT INTO ticket_issuance_inbox (event_id, event_type)
VALUES ($1, 'commerce.order-paid.v1')
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id
`

func (q *Queries) ClaimIssuanceEvent(ctx context.Context, eventID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimIssuanceEvent, eventID)
	var event_id pgtype.UUID
	err := row.Scan(&event_id)
	return event_id, err
}

const createIssuedTicket = `-- name: CreateIssuedTicket :exec
INSERT INTO issued_tickets (id, order_id, attendee_id, event_id, ticket_type_id, unit_index, qr_secret_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateIssuedTicketParams struct {
	ID           pgtype.UUID
	OrderID      pgtype.UUID
	AttendeeID   pgtype.UUID
	EventID      pgtype.UUID
	TicketTypeID pgtype.UUID
	UnitIndex    int32
	QrSecretHash []byte
}

func (q *Queries) CreateIssuedTicket(ctx context.Context, arg CreateIssuedTicketParams) error {
	_, err := q.db.Exec(ctx, createIssuedTicket,
		arg.ID,
		arg.OrderID,
		arg.AttendeeID,
		arg.EventID,
		arg.TicketTypeID,
		arg.UnitIndex,
		arg.QrSecretHash,
	)
	return err
}

const markIssuanceProcessed = `-- name: MarkIssuanceProcessed :exec
UPDATE ticket_issuance_inbox
SET status = 'processed', processed_at = now()
WHERE event_id = $1
`

func (q *Queries) MarkIssuanceProcessed(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markIssuanceProcessed, eventID)
	return err
}
