// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IssuedTicket struct {
	ID           pgtype.UUID
	OrderID      pgtype.UUID
	AttendeeID   pgtype.UUID
	EventID      pgtype.UUID
	TicketTypeID pgtype.UUID
	UnitIndex    int32
	QrSecretHash []byte
	Status       string
	IssuedAt     pgtype.Timestamptz
	QrToken      []byte
	CheckedInAt  pgtype.Timestamptz
	CheckedInBy  pgtype.UUID
}

type TicketCancellationInbox struct {
	MessageID   pgtype.UUID
	EventID     pgtype.UUID
	EventType   string
	ReceivedAt  pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
	Status      string
}

type TicketCancelledEvent struct {
	EventID               pgtype.UUID
	CancellationMessageID pgtype.UUID
	CancelledAt           pgtype.Timestamptz
}

type TicketCheckInOutbox struct {
	EventID       pgtype.UUID
	TicketID      pgtype.UUID
	EventType     string
	OccurredAt    pgtype.Timestamptz
	AggregateType string
	AggregateID   pgtype.UUID
	Payload       []byte
}

type TicketIssuanceInbox struct {
	EventID     pgtype.UUID
	EventType   string
	ReceivedAt  pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
	Status      string
}

type TicketRevocationOutbox struct {
	EventID       pgtype.UUID
	AggregateType string
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
}
