// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IssuedTicket struct {
	ID           pgtype.UUID
	OrderID      pgtype.UUID
	AttendeeID   pgtype.UUID
	EventID      pgtype.UUID
	TicketTypeID pgtype.UUID
	UnitIndex    int32
	QrSecretHash []byte
	Status       string
	IssuedAt     pgtype.Timestamptz
	QrToken      []byte
	CheckedInAt  pgtype.Timestamptz
	CheckedInBy  pgtype.UUID
}

type TicketCheckInOutbox struct {
	EventID     pgtype.UUID
	TicketID    pgtype.UUID
	EventType   string
	OccurredAt  pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type TicketIssuanceInbox struct {
	EventID     pgtype.UUID
	EventType   string
	ReceivedAt  pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
	Status      string
}
