export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const PASSWORD_VERIFIER = Symbol('PASSWORD_VERIFIER');

export const PASSWORD_RESET_CLAIM_LEASE_MS = 30_000;
export const PASSWORD_RESET_SESSION_BLOCK_TTL_MS = 5 * 60 * 1_000;
