export const ADMIN_CLIENT_ORIGIN = Symbol('ADMIN_CLIENT_ORIGIN');
export const ADMIN_IDENTITY_GRPC_CLIENT = Symbol('ADMIN_IDENTITY_GRPC_CLIENT');
export const ADMIN_IDENTITY_GRPC_DEADLINE_MS = Symbol(
  'ADMIN_IDENTITY_GRPC_DEADLINE_MS',
);
