export const PAYMENT_RECONCILIATION_BATCH_SIZE = 25;
export const PAYMENT_RECONCILIATION_CONCURRENCY = 5;
export const PAYMENT_RECONCILIATION_INTERVAL_MS = 30_000;
export const PAYMENT_RECONCILIATION_LEASE_MS = 120_000;
export const PAYMENT_RECONCILIATION_MAX_BACKOFF_MS = 30 * 60_000;
export const PAYMENT_RECONCILIATION_WAITING_INTERVAL_MS = 5 * 60_000;
