export const PAYMENT_ATTEMPT_REPOSITORY = Symbol('PAYMENT_ATTEMPT_REPOSITORY');
export const PAYMENT_MANAGEMENT = Symbol('PAYMENT_MANAGEMENT');
export const PAYMENT_PROVIDER_PORT = Symbol('PAYMENT_PROVIDER_PORT');
export const PAYMENT_PROVIDER_EVENT_HANDLING = Symbol(
  'PAYMENT_PROVIDER_EVENT_HANDLING',
);
export const PAYMENT_WEBHOOK_VERIFIER = Symbol('PAYMENT_WEBHOOK_VERIFIER');
