export const PAYMENT_ATTEMPT_REPOSITORY = Symbol('PAYMENT_ATTEMPT_REPOSITORY');
export const PAYMENT_MANAGEMENT = Symbol('PAYMENT_MANAGEMENT');
export const PAYMENT_PROVIDER_PORT = Symbol('PAYMENT_PROVIDER_PORT');
