export {
  EVENT_SERVICE_NAME,
  EVENTA_EVENT_V1_PACKAGE_NAME,
  EventServiceControllerMethods,
  type EventServiceClient,
  type EventServiceController,
} from '../../generated/eventa/event/v1/event_service.generated';
export {
  AdminEventSort,
  EventStatus,
  EventMediaSlot,
  EventMediaUploadStatus,
  type AdminEventSummary,
  type AddEventTicketTypeRequest,
  type AddEventTicketTypeResponse,
  type CreateEventMediaUploadRequest,
  type CreateEventMediaUploadResponse,
  type CreateEventTicketTypeRequest,
  type CreateEventTicketTypeResponse,
  type DefineEventTicketCurrencyRequest,
  type DefineEventTicketCurrencyResponse,
  type CreateDraftEventRequest,
  type CreateDraftEventResponse,
  type Event,
  type EventMedia,
  type EventTicketType,
  type EventTicketCurrency,
  type GetAdminEventRequest,
  type GetAdminEventResponse,
  type GetEventMediaUploadRequest,
  type GetEventMediaUploadResponse,
  type GetPublishedEventRequest,
  type GetPublishedEventResponse,
  type GetEventTicketCatalogueRequest,
  type GetEventTicketCatalogueResponse,
  type ListAdminEventsRequest,
  type ListAdminEventsResponse,
  type ListEventTicketTypesRequest,
  type ListEventTicketTypesResponse,
  type PublishedEvent,
  type PublishEventRequest,
  type PublishEventResponse,
  type RetireDraftEventRequest,
  type RetireDraftEventResponse,
  type RetireEventTicketTypeRequest,
  type RetireEventTicketTypeResponse,
  type RemoveEventMediaRequest,
  type RemoveEventMediaResponse,
  type UpdateDraftEventRequest,
  type UpdateDraftEventResponse,
  type UpdateEventTicketTypeRequest,
  type UpdateEventTicketTypeResponse,
  type Venue,
} from '../../generated/eventa/event/v1/event.generated';
export * from './proto-paths';
