version: '3'
tasks:
  build: go build ./...
  test:
    cmds:
      - go test -short ./...
      - go test ./test/integration/...
  test:unit: go test -short ./...
  test:integration: go test ./test/integration/...
  lint: golangci-lint run
  fmt: gofmt -w cmd internal test
  migrate:
    cmds:
      - docker compose -f ../../compose.yaml up -d --wait notification-database
      - go run ./cmd/notification-migration
