export const EVENT_MANAGEMENT = Symbol('EVENT_MANAGEMENT');
export const EVENT_MEDIA_MANAGEMENT = Symbol('EVENT_MEDIA_MANAGEMENT');
export const EVENT_MEDIA_OBJECT_STORAGE = Symbol('EVENT_MEDIA_OBJECT_STORAGE');
export const EVENT_MEDIA_UPLOAD_REPOSITORY = Symbol(
  'EVENT_MEDIA_UPLOAD_REPOSITORY',
);
export const EVENT_MEDIA_MUTATION_REPOSITORY = Symbol(
  'EVENT_MEDIA_MUTATION_REPOSITORY',
);
export const EVENT_MEDIA_OBJECT_DELETION_REPOSITORY = Symbol(
  'EVENT_MEDIA_OBJECT_DELETION_REPOSITORY',
);
export const EVENT_MEDIA_OBJECT_DELETION_JOB_PUBLISHER = Symbol(
  'EVENT_MEDIA_OBJECT_DELETION_JOB_PUBLISHER',
);
export const EVENT_MEDIA_VERIFICATION_JOB_PUBLISHER = Symbol(
  'EVENT_MEDIA_VERIFICATION_JOB_PUBLISHER',
);
export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER');
export const EVENT_PUBLICATION_OUTBOX = Symbol('EVENT_PUBLICATION_OUTBOX');
export const EVENT_PUBLICATION_OUTBOX_BATCH_SIZE = 25;
export const EVENT_PUBLICATION_OUTBOX_CLAIM_TTL_MS = 30_000;
export const EVENT_PUBLICATION_OUTBOX_POLL_INTERVAL_MS = 1_000;
