export const EVENT_MANAGEMENT = Symbol('EVENT_MANAGEMENT');
export const EVENT_TICKET_TYPE_MANAGEMENT = Symbol(
  'EVENT_TICKET_TYPE_MANAGEMENT',
);
export const EVENT_TICKET_TYPE_REPOSITORY = Symbol(
  'EVENT_TICKET_TYPE_REPOSITORY',
);
export const EVENT_TICKET_TYPE_LIMIT = 20;
export const EVENT_CAPACITY_RESERVATION_MANAGEMENT = Symbol(
  'EVENT_CAPACITY_RESERVATION_MANAGEMENT',
);
export const EVENT_CAPACITY_RESERVATION_REPOSITORY = Symbol(
  'EVENT_CAPACITY_RESERVATION_REPOSITORY',
);
export const EVENT_CAPACITY_RESERVATION_TTL_MINUTES = 10;
export const EVENT_CAPACITY_LOCK_TIMEOUT_MS = 2_000;
export const EVENT_CAPACITY_EXPIRY_BATCH_SIZE = 100;
export const EVENT_CAPACITY_EXPIRY_INTERVAL_MS = 1_000;
export const EVENT_WAITLIST_MANAGEMENT = Symbol('EVENT_WAITLIST_MANAGEMENT');
export const EVENT_WAITLIST_REPOSITORY = Symbol('EVENT_WAITLIST_REPOSITORY');
export const EVENT_WAITLIST_ACTIVE_LIMIT = 10_000;
export const EVENT_WAITLIST_PROMOTION_BATCH_SIZE = 100;
export const EVENT_WAITLIST_PROMOTION_INTERVAL_MS = 1_000;
export const EVENT_WAITLIST_OPPORTUNITY_MINUTES = 15;
export const EVENT_CATEGORY_LIMIT = 5;
export const EVENT_LIST_DEFAULT_PAGE_SIZE = 20;
export const EVENT_LIST_MAX_PAGE_SIZE = 50;
export const EVENT_MEDIA_MANAGEMENT = Symbol('EVENT_MEDIA_MANAGEMENT');
export const EVENT_MEDIA_OBJECT_STORAGE = Symbol('EVENT_MEDIA_OBJECT_STORAGE');
export const EVENT_MEDIA_UPLOAD_REPOSITORY = Symbol(
  'EVENT_MEDIA_UPLOAD_REPOSITORY',
);
export const EVENT_MEDIA_MUTATION_REPOSITORY = Symbol(
  'EVENT_MEDIA_MUTATION_REPOSITORY',
);
export const EVENT_MEDIA_OBJECT_DELETION_REPOSITORY = Symbol(
  'EVENT_MEDIA_OBJECT_DELETION_REPOSITORY',
);
export const EVENT_MEDIA_OBJECT_DELETION_JOB_PUBLISHER = Symbol(
  'EVENT_MEDIA_OBJECT_DELETION_JOB_PUBLISHER',
);
export const EVENT_MEDIA_VERIFICATION_JOB_PUBLISHER = Symbol(
  'EVENT_MEDIA_VERIFICATION_JOB_PUBLISHER',
);
