export const ATTENDEE_SESSION_STATE = Symbol('ATTENDEE_SESSION_STATE');

export const ATTENDEE_SESSION_TTL_MS = 7 * 24 * 60 * 60 * 1_000;
export const ATTENDEE_SESSION_MAX_CONCURRENT = 3;
export const ATTENDEE_SESSION_TOKEN_BYTES = 32;
