export const ATTENDEE_DELETION_REPOSITORY = Symbol(
  'ATTENDEE_DELETION_REPOSITORY',
);
export const ATTENDEE_DELETION_PREPARATION_TTL_MS = 5 * 60 * 1_000;
export const ATTENDEE_DELETION_BARRIER_TTL_MS = 7 * 24 * 60 * 60 * 1_000;
