export const ATTENDEE_EMAIL_VERIFICATION_REPOSITORY = Symbol(
  'ATTENDEE_EMAIL_VERIFICATION_REPOSITORY',
);
export const EMAIL_VERIFICATION_OTP_STATE = Symbol(
  'EMAIL_VERIFICATION_OTP_STATE',
);
export const EMAIL_VERIFICATION_JOB_PUBLISHER = Symbol(
  'EMAIL_VERIFICATION_JOB_PUBLISHER',
);

export const EMAIL_VERIFICATION_OTP_LENGTH = 6;
export const EMAIL_VERIFICATION_OTP_TTL_MS = 15 * 60 * 1_000;
export const EMAIL_VERIFICATION_OTP_MAX_GUESSES = 5;
export const EMAIL_VERIFICATION_RESEND_COOLDOWN_MS = 60 * 1_000;
