export const ATTENDEE_EMAIL_VERIFICATION_REPOSITORY = Symbol(
  'ATTENDEE_EMAIL_VERIFICATION_REPOSITORY',
);
export const ATTENDEE_EMAIL_VERIFICATION_SERVICE = Symbol(
  'ATTENDEE_EMAIL_VERIFICATION_SERVICE',
);
export const EMAIL_VERIFICATION_OTP_STORE = Symbol(
  'EMAIL_VERIFICATION_OTP_STORE',
);
export const EMAIL_VERIFICATION_REDIS_CLIENT = Symbol(
  'EMAIL_VERIFICATION_REDIS_CLIENT',
);

export const EMAIL_VERIFICATION_OTP_LENGTH = 6;
export const EMAIL_VERIFICATION_OTP_TTL_MS = 15 * 60 * 1_000;
export const EMAIL_VERIFICATION_OTP_MAX_GUESSES = 5;
export const EMAIL_VERIFICATION_RESEND_COOLDOWN_MS = 60 * 1_000;
