export const ATTENDEE_PASSWORD_RESET_REPOSITORY = Symbol(
  'ATTENDEE_PASSWORD_RESET_REPOSITORY',
);
export const PASSWORD_RESET_CODE_STATE = Symbol('PASSWORD_RESET_CODE_STATE');

export const PASSWORD_RESET_CODE_TTL_MS = 15 * 60 * 1_000;
export const PASSWORD_RESET_CODE_MAX_GUESSES = 5;
export const PASSWORD_RESET_REQUEST_COOLDOWN_MS = 60 * 1_000;
