export const ATTENDEE_DELETION_REPOSITORY = Symbol(
  'ATTENDEE_DELETION_REPOSITORY',
);
export const ATTENDEE_LIFECYCLE_OUTBOX = Symbol('ATTENDEE_LIFECYCLE_OUTBOX');
export const ATTENDEE_LIFECYCLE_EVENT_PUBLISHER = Symbol(
  'ATTENDEE_LIFECYCLE_EVENT_PUBLISHER',
);

export const ATTENDEE_DELETION_PREPARATION_TTL_MS = 5 * 60 * 1_000;
export const ATTENDEE_DELETION_BARRIER_TTL_MS = 7 * 24 * 60 * 60 * 1_000;
export const ATTENDEE_LIFECYCLE_OUTBOX_BATCH_SIZE = 25;
export const ATTENDEE_LIFECYCLE_OUTBOX_CLAIM_TTL_MS = 30_000;
export const ATTENDEE_LIFECYCLE_OUTBOX_POLL_INTERVAL_MS = 1_000;
