debezium.sink.type=kafka
debezium.sink.kafka.producer.bootstrap.servers=event-bus:9092
debezium.sink.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
debezium.sink.kafka.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer
debezium.sink.kafka.producer.acks=all
debezium.sink.kafka.producer.enable.idempotence=true

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=commerce-database
debezium.source.database.port=5432
debezium.source.database.user=${POSTGRES_USER}
debezium.source.database.password=${POSTGRES_PASSWORD}
debezium.source.database.dbname=${POSTGRES_DB}
debezium.source.topic.prefix=eventa-commerce-kafka-cdc
debezium.source.plugin.name=pgoutput
debezium.source.slot.name=eventa_commerce_kafka_cdc
debezium.source.publication.name=eventa_commerce_kafka_cdc
debezium.source.publication.autocreate.mode=filtered
debezium.source.table.include.list=public.commerce_order_outbox
debezium.source.tombstones.on.delete=false
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=1000

debezium.format.key=simplestring
debezium.format.value=json
debezium.format.value.schemas.enable=false
debezium.transforms=outbox
debezium.transforms.outbox.type=io.debezium.transforms.outbox.EventRouter
debezium.transforms.outbox.route.by.field=aggregate_type
debezium.transforms.outbox.route.topic.replacement=$${routedByValue}
debezium.transforms.outbox.table.field.event.id=event_id
debezium.transforms.outbox.table.field.event.key=aggregate_id
debezium.transforms.outbox.table.field.event.payload=payload
debezium.transforms.outbox.table.field.event.type=event_type
debezium.transforms.outbox.table.expand.json.payload=true
debezium.transforms.outbox.table.op.invalid.behavior=fatal
